apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name_unencrypted }}
  labels:
    app: {{ .Values.name_unencrypted }}
type: Opaque
data:
{{- range $key, $val := .Values.secrets }}
  {{ $key }}: {{ $val | b64enc | quote }}
{{- end }}
